baseURL = 'https://heathrelease.github.io/'
locale = 'zh-CN'
title = "Heath's Blog"
hasCJKLanguage = true
enableRobotsTXT = true

[params]
description = "Heath's Blog"

[pagination]
pagerSize = 6

[taxonomies]
tag = 'tags'
